# Generated by Django 3.2.25 on 2024-04-08 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='is_paied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booktime',
            name='paied_with',
            field=models.CharField(choices=[('عند الحضور', 'عند الحضور'), ('فودافون كاش', 'فودافون كاش')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_warning', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_of_paying_in_minuts', models.IntegerField(default=0)),
                ('limit_of_canceling_in_minuts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
