# Generated by Django 3.2.25 on 2024-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240408_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='paied_with',
            field=models.CharField(choices=[('عند الحضور', 'عند الحضور'), ('فودافون كاش', 'فودافون كاش')], max_length=255),
        ),
    ]
